import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NavBar from "../components/nav-bar";
import SideBar from "../components/side-bar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "cgallery",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <NavBar />
        <div className="flex container">
          <SideBar />

          <div className="w-full pt-6">{children}</div>
        </div>
      </body>
    </html>
  );
}
